### ISSUE TITLE
[FEAT] 주문 모듈 개발

### ISSUE THREAD

**Issue by stae1102** [5th-wanted-pre-onboarding-teamG/2_shopping_mall_management#39]
# 기능

### C

- [x] 주문하기: POST /orders

### R

- [x] 주문내역 전체 검색: GET /orders
- [x] 주문자명으로 검색: GET /orders/:name/users
- [x] 주문상태, 시작일자, 종료일자 필터링: GET /orders?state=&startDate=&endDate=

### U

- [x] 주문상태 변경: PATCH /orders/:orderId?state=

### D

- [x] 주문 취소: DELETE /orders/:orderId/cancel
- [x] 주문내역 삭제: DELETE /orders/:orderId

### C

<details>
  <summary>주문하기</summary>
  <div markdown="1">
  ! 표시는 필수값

  - 바디
    - **userId**!: 유저 아이디(세션에 저장된 값 사용해도 됨)
    - **productId**!: 상품 아이디
    - **countryId**!: 국적 아이디
    - **quantity**!: 수량
    - **city**!: 배송지 도시
    - **zipCode**!: 우편번호
    - _OwnedCouponId?:_ 사용자 쿠폰 아이디
    - _name?_: 받는사람 이름
    - _phone?_: 받는사람 연락처

  </div>
</details>

### R

주문내역 전체 검색: 자신의 주문 내역을 전체조회
- 유저 데코레이터를 통해 별도의 경로는 설정하지 않습니다.

주문자명 검색: 주문자명으로 주문 내역을 검색합니다.
- 논의
  - [x] 판매자가 검색하는 경우: 원하는 유저의 주문내역 중에서 해당 상품을 구매한 내역
  - [x] 운영자가 검색하는 경우: 원하는 유저의 모든 주문내역

주문상태, 시작일자, 종료일자 필터링
- Query
  - state: 주문상태
  - startDate: 시작일
  - endDate: 종료일

### U

주문상태 변경: 주문상태를 변경합니다.
- 주문상태를 변경한다는 게 판매자가 지정하는 거겠죠??
- 유저 권한 파악
- Body (POST, PUT, PATCH 등은 요청 바디를 필요로 합니다)
  - state: 주문상태

### D

<details>
  <summary>주문 취소</summary>
  <div markdown="1">

  주문을 취소합니다.

  📌 고려할 것
    1. 결제 취소와 같이 처리
    2. 쿠폰 내역 초기화
    3. 재고 수정

  </div>
</details>

<details>
  <summary>주문 내역 삭제</summary>
  <div markdown="1">

  주문 내역을 삭제합니다.

  📌 고려할 것
  **주문 내역만 삭제**, 결제 내역은 보존 

  </div>
</details>

## 부가기능 추가

주문 변경에서 주문 수량을 변경한다거나 받는 사람을 변경하는 등 다양한 수정을 고려해볼 수 있겠습니다~

## REST API

POST /orders
GET /orders
GET /orders/:name/user
GET /orders?state=&startDate=&endDate=
PATCH /orders/:orderId?state=
DELETE /orders/:orderId
DELETE /orders/:orderId/cancel (약간 functional)

## 추후 적용

- 레포지토리를 사용자 정의로 만들어서 기본적인 함수들을 미리 정리해서 서비스 파일코드 간략히 하기
https://hou27.tistory.com/entry/Custom-repository%EC%82%AC%EC%9A%A9%EC%9E%90-%EC%A0%95%EC%9D%98-%EB%A0%88%ED%8F%AC%EC%A7%80%ED%86%A0%EB%A6%AC-typeORM

**Comment by stae1102** [comment]
# C: 주문하기 실행

## 소스코드

<details>
  <summary>소스코드</summary>
  <div markdown="1">

  ```ts
  // 고려할 것
  // 결제 테이블(주문아이디, 총 상품 가격, 총 할인 금액, 결제금액) 미리 레코드 하나 생성 ✅
  // 상품 테이블(재고 -1) ✅
  // 사용자 보유 쿠폰 테이블(쿠폰 사용날짜 저장) ✅
  async createOrder(user: Users, createOrderDto: CreateOrderDto) {
    const queryRunner = this.dataSource.createQueryRunner();

    // 트랜잭션 시작
    await queryRunner.connect();
    await queryRunner.startTransaction();

    // 서비스 구현
    try {
      // 상품 가격 조회
      let { price: productPrice } = await queryRunner.manager.getRepository(Products).findOne({
        where: { productId: createOrderDto.productId },
        select: ['price'],
      });

      // 배송비 조회
      let { price: deliveryPrice } = await queryRunner.manager.getRepository(DeliveryCosts).findOne({
        where: { deliveryCostId: createOrderDto.deliveryCostId },
        select: ['price'],
      });

      // 국가명 탐색
      const { name: country } = await queryRunner.manager.getRepository(Countries).findOne({
        where: { countryId: createOrderDto.countryId },
        select: ['name'],
      });

      // 총 할인 가격
      let discountedPrice = 0;

      // 쿠폰이 존재하는 경우
      if (createOrderDto.ownedCouponId) {
        // 쿠폰 아이디를 통해 쿠폰 타입 및 할인 정보 저장
        const { couponType, discount } = await queryRunner.manager
          // .getRepository(Coupons)
          // .findOne({ where: { couponId }, select: ['couponType', 'salePrice'] });
          .getRepository(Coupons)
          .createQueryBuilder('coupons')
          .innerJoin('coupons.OwnedCoupons', 'ownedCoupons')
          .where('ownedCoupons.ownedCouponId = :ownedCouponId', {
            ownedCouponId: createOrderDto.ownedCouponId,
          })
          .getOne();

        // 쿠폰 종류에 따라, 총 할인 가격 및 할일된 가격 계산
        switch (couponType) {
          case CouponType.DELIVERY:
            discountedPrice = deliveryPrice * (discount / 100);
            deliveryPrice -= discountedPrice;
            break;
          case CouponType.PERCENT:
            discountedPrice = productPrice * (discount / 100);
            productPrice -= discountedPrice;
            break;
          case CouponType.FLAT_RATE:
            discountedPrice = discount;
            productPrice -= discountedPrice;
            break;
        }
      }

      // 주문 내역 작성
      const newOrder = await queryRunner.manager.getRepository(Orders).save({
        UserId: user.userId,
        ProductId: createOrderDto.productId,
        DeliveryCostId: createOrderDto.deliveryCostId,
        orderState: OrderState.PAYMENT_WAITING,
        quantity: createOrderDto.quantity,
        address: { country, city: createOrderDto.city, zipcode: createOrderDto.zipCode },
        recipientName: createOrderDto.name || '',
        recipientPhone: createOrderDto.phone || '',
      });

      // 결제 내역 생성
      const newPayment = await queryRunner.manager.getRepository(Payments).save({
        OrderId: newOrder.orderId,
        paymentState: PaymentState.COMPLETE,
        orderPrice: productPrice * createOrderDto.quantity + deliveryPrice,
        discountedPrice,
        paymentPrice: productPrice * createOrderDto.quantity + deliveryPrice + discountedPrice,
      });

      // 쿠폰 사용처리
      await queryRunner.manager.update(
        OwnedCoupons,
        { ownedCouponId: createOrderDto.ownedCouponId },
        { usedDate: new Date(), OrderId: newOrder.orderId },
      );

      await queryRunner.manager
        .createQueryBuilder()
        .update(Products)
        .set({ stock: () => 'stock - 1' })
        .where('productId = :productId', { productId: createOrderDto.productId })
        .execute();
      await queryRunner.commitTransaction();
    } catch (error) {
      await queryRunner.rollbackTransaction();
      throw new BadRequestException('주문 과정에서 오류가 발생했습니다.');
    } finally {
      await queryRunner.release();
    }
  }

  async getMyOrders(userId: number) {
    return await this.ordersRepository.find({
      where: { UserId: userId },
    });
  }

  async getOrdersByName(name: string) {
    const result = this.dataSource
      .getRepository(Users)
      .createQueryBuilder('users')
      .innerJoinAndSelect('users.Orders', 'orders')
      .where('users.name = :name', { name })
      .select('users.Orders');
    // .getMany();

    return result;
  }
  ```
  </div>
</details>

## 1. 쿠폰 없이 주문

### 요청 및 응답

<img width="702" alt="image" src="https://user-images.githubusercontent.com/83271772/199477299-96be0583-7350-4425-a7e8-7a840dd6e975.png">

### 데이터베이스 레코드 생성

#### 1. 주문내역

<img width="936" alt="image" src="https://user-images.githubusercontent.com/83271772/199477403-20b9a747-4f22-4890-aa78-68ef5e76f2c5.png">

#### 2. 결제 내역

<img width="918" alt="image" src="https://user-images.githubusercontent.com/83271772/199477564-b0dcff5d-49d0-4cc5-bf13-68683b3e498f.png">

productId 1번은 맥북이며, 가격은 1,350,000원, deliveryCost에서의 배송비는 26000원 => 1,376,000

#### 3. 제품 재고

<img width="931" alt="image" src="https://user-images.githubusercontent.com/83271772/199477826-fe2136dd-03a0-47a2-9ee7-1f3323f82986.png">

테스트를 두 번 하여 100개에서 98개로 줄음

#### 4. 쿠폰 사용

<img width="934" alt="image" src="https://user-images.githubusercontent.com/83271772/199478197-684f672f-13d6-4338-b22c-9b9f453d7727.png">

아무 쿠폰도 안 사용했으므로 값이 바뀌지 않음
@loveAlakazam @eunkangchoi 쿠폰 사용날짜의 기본값을 제거해주세요~

## 2. 배송비 쿠폰 사용(50% 할인으로 테스트)

### 요청 및 응답

<img width="703" alt="image" src="https://user-images.githubusercontent.com/83271772/199478535-a96decbc-08d8-4aa9-bb83-ac6e4495da70.png">

### 데이터베이스 레코드 생성

#### 1. 주문내역

<img width="935" alt="image" src="https://user-images.githubusercontent.com/83271772/199478678-a0cb3185-2416-4021-a224-4107ec37d3e2.png">

#### 2. 결제내역

<img width="922" alt="image" src="https://user-images.githubusercontent.com/83271772/199478804-87bf72b2-11c7-4888-a647-edf94f407b3a.png">

#### 3. 제품재고

<img width="933" alt="image" src="https://user-images.githubusercontent.com/83271772/199478907-ef0d9ba8-916b-40d0-9572-2794d4afe447.png">

정상적으로 1개 더 줄어듦

#### 4. 쿠폰사용

<img width="933" alt="image" src="https://user-images.githubusercontent.com/83271772/199478985-02d7ff30-5d33-4adc-a4c4-1d4fc6482164.png">

1번 행의 사용날짜가 새롭게 갱신됨

## 3. 정액제 할인(10000원으로 가정)

### 요청 및 응답

<img width="704" alt="image" src="https://user-images.githubusercontent.com/83271772/199479090-8df7b8d8-58d8-4a87-9787-d351fb608794.png">

### 데이터베이스 레코드 생성

#### 1. 주문내역

<img width="944" alt="image" src="https://user-images.githubusercontent.com/83271772/199479337-66d8db01-7422-4443-ac39-a7da031a8488.png">

#### 2. 결제내역

<img width="927" alt="image" src="https://user-images.githubusercontent.com/83271772/199479398-3fb0b2d7-a586-4e5b-893a-2f2013fa7466.png">

#### 3. 재고

<img width="932" alt="image" src="https://user-images.githubusercontent.com/83271772/199479450-5d711b66-cde2-47ef-af1e-4edd49e810a7.png">

#### 4. 쿠폰사용

<img width="933" alt="image" src="https://user-images.githubusercontent.com/83271772/199479526-cc4f5258-ad76-408e-96b6-3eaa32eb2af9.png">

정상적으로 갱신됨

## 4. 퍼센트 할인

### 요청 및 응답

<img width="707" alt="image" src="https://user-images.githubusercontent.com/83271772/199480148-bc65ef71-d108-4190-953f-af73ccf16d00.png">

### 데이터베이스 레코드 생성

#### 1. 주문내역

**7번 행입니다.**

<img width="943" alt="image" src="https://user-images.githubusercontent.com/83271772/199480215-40b1038d-5a39-4eb4-b2b1-b345749f507f.png">

#### 2. 결제내역

<img width="931" alt="image" src="https://user-images.githubusercontent.com/83271772/199480331-a2ce22b9-308c-41ef-8923-7f8a6de285f9.png">

`총 가격과 결제 가격을 반대로 써서 이 부분은 고쳐야 하네요.`

#### 3. 재고

<img width="919" alt="image" src="https://user-images.githubusercontent.com/83271772/199480486-c53ae900-7ea5-40cf-ba07-f5b2685dc4a4.png">

맥북을 7번 주문했으므로 이상 없습니다.

#### 4. 쿠폰사용

<img width="935" alt="image" src="https://user-images.githubusercontent.com/83271772/199480570-83b24441-1aa7-4c9d-8122-c4d0e310c946.png">

정상적으로 갱신됨

# 개선사항

- [ ] 1. 총 가격과 결제 가격 저장 수정하기
- [ ] 2. 쿠폰의 usedDate 기본값 없애기
- [ ] 3. 주문내역과 결제내역을 동시에 해도 되는지 논의
- [ ] 4. 3번이 맞다면 결제 테이블의 결제 상태를 어떻게 할지 논의(주문내역의 결제 대기를 결제내역으로 옮기고 주문내역에는 결제 확인중 넣기 등)
- [ ] 5. 바디값에 deliveryCostId를 뺄지 논의(countryId와 quantity로 구할 수 있음)

---

주문하기가 너무 빡세서 일단 확인 한 번만 부탁드립니다🥲

@loveAlakazam 
@wlsgml719 
@nuobasic
@MisterRuby

**Comment by stae1102** [comment]
제가 9시에 동아리 프로젝트 회의가 있어서 일단 이슈에 지금까지 한 것들 정리해서 올려요!!

**Comment by loveAlakazam** [comment]
# 완료

- [x] ownedCoupons테이블의 **usedDate컬럼** 기본값을  `null`로 수정했습니다.

### 체리픽 대상

- 작업 브랜치: feature/issue-32 (#32 )

| 커밋 로그 아이디 |  커밋명 | 설명 |
|:--------------:|:------:|:----:|
| `672a43ad6da9ee32fce1993f1b0b76204f0619cf` |  chore: Coupons 엔티티 각 컬럼별 comment 추가 | Coupns.ts 에 있는 주요컬럼에 comment 옵션 추가  |
| `0624be438d1420102fa57308de064737fa8976f6` | fix: OwnedCoupons 기본값 수정 | usedDate, expirationDate 컬럼 기본값  null 로 수정, nullable 로 설정 |

위의 커밋로그 아이디를 체리픽해보시길 바래요 :)


# 진행중

- [ ] 쿠폰을 사용하게되면, usedDate값이 쿠폰사용요청 날짜로 변경하도록 하겠습니다.

**Comment by wlsgml719** [comment]
주문 내역 작성과 결제 내역 작성이 동시에 처리되어서
orders의 state는 결제대기이고,
payment의 state는 결제완료가 됩니다.

관계상 분리해서 order 생성한 후
별도로 payment를 호출해서 처리해야할 것 같아요!

이 부분은 용범님과 논의가 필요해보입니다!
@MisterRuby

**Comment by MisterRuby** [comment]
주문 생성시에는 주문만 생성하면 됩니다. 새로 생성된 주문은 결제 대기입니다.

주문의 상태를 결제 완료로 바꾸는 것과 쿠폰을 사용한 상태로 바꾸는 것은 결제를 생성하는 시점에 처리해야할 것 같습니다.

**Comment by stae1102** [comment]
이게 좀 긴가민가한 부분이었는데 그러면 일반적으로 옥션이나 지마켓에서 주문과 동시에 결제를 진행하는데, 이게 아니라 발주 넣듯이 주문만 넣고 있는 느낌으로 이해하면 될까요?

**Comment by MisterRuby** [comment]
넵 일단 그렇게 진행해야할 것 같습니다.
만약 주문쪽에서 결제 생성까지 한다면 결제 쪽 상태에 결제대기를 추가로 넣고 진행할 수도 있는데 그러면 지금 상태에서 주문 생성 부담이 너무 커질 것 같습니다.

**Comment by stae1102** [comment]
아 그러면 괜히 어렵게 했네요 😔

그렇다면 결제 내역은 그대로 두고 재고만 일단 -1해두는 것으로 하고

결제 모듈에서 결제 내역을 작성하고, 결제하면서 쿠폰도 사용하는 방향으로 분류할까요?
혹시 도움이 될 수도 있으니까 해당 이슈 소스코드는 보존해놓겠습니다!

**Comment by MisterRuby** [comment]
넵 저도 그쪽 방향으로 개발을 진행해서 일단 이렇게 진행하고 추후에 개선할 수 있으면 그 때 다시 이야기해보죠.
